### ISSUE TITLE
Unable to specify query function without arguments

### ISSUE THREAD

**Issue by shader** [hyperledger/fabric-chaintool#13]
I'm trying to build a chaincode that supports several basic 'get' functions that don't need any arguments.

How do I specify and implement such a function? I have tried both `RecordResult GetRecord(void) = 1;` and `RecordResult GetRecord() = 1;`

**Comment by ghaskins** [comment]
I apologize,@shader.  I somehow missed the email notification for your question.

The short answer is: you can't today.  The long answer is, this is perfectly reasonable request.  I will file a bug and get this fixed.

**Comment by ghaskins** [comment]
@shader the issue is fixed as of PR #16
