### ISSUE TITLE
Add "chaintool env" command

### ISSUE THREAD

**Issue by bmatsuo** [hyperledger/fabric-chaintool#37]
I like to edit Go projects in the vim/nvim text editor, for which I have installed the "vim-go" plugin installed. But, this doesn't work very well by default when I am working on chaintool-based chaincode applications. Because chaintool builds projects using a custom/non-default value for GOPATH many features in the editor/plugin break unless I explicitly set GOPATH in the vim process.

This problem is obviously not specific to vim. Editor/IDE plugins need to know the GOPATH for a project in order to function correctly.

I think the most basic/general way to improve the integration of chaintool with editors/IDEs and even other go tooling is to have a command that prints the project's build-GOPATH.

Examples

```sh
> # Just print the value of GOPATH to stdout
> chaintool env
GOPATH=/path/to/project/build/deps:/path/to/project/build:/path/to/project

> # Launch vim using the project GOPATH
> env $(chaintool env) vim src/chaincode/chaincode.go

> # Run go test using the project GOPATH
> env $(chaintool env) go test ./src/chaincode
```

**Comment by ghaskins** [comment]
This is a great idea! Thanks.  It reminds me of "docker-engine env", which works well.  I am constantly setting up the GOPATH in the IDE for chaintool projects, but it never occurred to me to automate it as much as possible.  Should be easy to add.

**Comment by bmatsuo** [comment]
Interesting re: `docker-engine env`. I wasn't really aware of much prior art with this kind of stuff. Definitely take good ideas from other projects though. Improve on my suggestion if need be.
