### ISSUE TITLE
example02/client/rest/cljs should set explicit constraint on leiningen 2.0+

### ISSUE THREAD

**Issue by ghaskins** [hyperledger/fabric-chaintool#8]
Currently, we have no explicit constraint but older versions of lein are not likely to work resulting in really ugly stack traces when things go south.  Lets fix this so at least users with older leiningen installs get a helpful error message.

@jranz303

**Comment by ecb** [comment]
The committed fix issues a warning during  'lein cljsbuild once' command. An error might be preferable but that doesn't seem to be an option.
